contents:
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - wolfictl-head
    - coreutils
    - bash
    - busybox
    - gitsign
    - make
    - graphviz
    - git

entrypoint:
  command: /usr/bin/wolfictl

cmd: -h
